### ISSUE TITLE
HTML option instead image

### ISSUE THREAD

**Issue by thiagocoelho** [marmat/google-maps-api-addons#23]
Hi :)

I was wondering if would be possible to develop a way to use custom html as markers instead image only.

I'm about to test a solution like creating all necessary markers using PanoMarker, then appending custom html markers inside the panorama div container.

Basically I could track the position of each pano marker using pov_changed event, applying those values to my custom divs that would follow the same position of PanoMarkers inside the panorama.

There is any other way to do it?

Thank you.

**Comment by marmat** [comment]
Hi Thiago, 

you can modify the `onAdd`/`Remove` methods in order to do something other than creating a div and sticking an image inside it. 

If you don't want to modify the PanoMarker source directly in your application (in case you want to maintain the ability to sync updates easily), you can create a subclass (the same way PanoMarker is a [subclass of OverlayView](https://github.com/marmat/google-maps-api-addons/blob/master/panomarker/src/panomarker.js#L147)) and just override the `onAdd`/`Remove` methods (and possibly `draw`? depending on what you want to do. But ideally you'll just want to change whatever happens inside `this.marker_`, that way all the positioning should be taken care of by PanoMarker).

**Comment by thiagocoelho** [comment]
Thank you @marmat!

I'm working on this and soon as I get a solution I'm gonna show you.
