### ISSUE TITLE
Performance is poor

### ISSUE THREAD

**Issue by A13xs** [marmat/google-maps-api-addons#25]
I created a test case and SimpleMarker performance is poor.

Can you check whether the test is correct?

http://jsperf.com/google-maps-marker-vs-simplymarker

**Comment by marmat** [comment]
Hi A13xs,

SimpleMarker was written at a time when Google's Markers were extremely bloated and heavy s.t. rendering hundreds or thousands of them on a single map was very difficult.

With the newer versions of the Maps API, it has gotten *much* better. I believe one of the reasons is because the markers are now drawn on a canvas instead of being represented by real DOM nodes, but I'm not entirely sure.

In any case, yes, it can very well be that SimpleMarker is now (much) slower than Google's implementation, at this point there's probably now benefit in using SimpleMarker for new projects.

Thanks,
Martin
